### ISSUE TITLE
手机写博客啦，真好！

### ISSUE THREAD

**Issue by islwei** [islwei/islwei.github.io#2]
https://lweigithub.github.io/2018/09/30/create-post-by-ios/ 

 ##手机写博客APP名字叫CodeHub也是GitHub上的一个工程文本编辑器略难用。。。其他在测试

**Comment by lweiGitHub** [comment]
手机回复还成 写md真心难受

**Comment by lweiGitHub** [comment]
是时候整一个MD模板生成tool了
